# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - "@FOSCKEditor/Form/ckeditor_widget.html.twig"

fos_ck_editor:
    configs:
        my_config:
            toolbar: standard

easy_admin:
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
