twig:
    default_path: "%kernel.project_dir%/templates"
    form_themes: ["bootstrap_5_layout.html.twig"]

    date:
        timezone: Europe/Berlin

    paths:
        # point this wherever your css files live
        "%kernel.project_dir%/assets/styles": styles

    globals:
        app_cookie_consent: "%app.cookie_consent%"
        app_registration: "%app.registration%"
        app_terms: "%app.terms%"
        app_title: "%app.title%"
