twig:
    default_path: "%kernel.project_dir%/templates"
    form_themes: ["bootstrap_4_layout.html.twig"]

    date:
        timezone: Europe/Berlin

    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/assets/styles': styles
