twig:
    default_path: "%kernel.project_dir%/templates"
    form_themes: ["bootstrap_5_layout.html.twig"]

    date:
        timezone: Europe/Berlin

    paths:
        # point this wherever your css files live
        "%kernel.project_dir%/assets/styles": styles

    globals:
        app_allow_registration: "%app.registration%"
        app_cookie_consent: "app.cookie_consent"
