name: app

type: php:8.1

runtime:
    extensions:
        - xsl
        - mbstring
        - sodium
        - ctype
        - iconv
        - pdo_mysql

relationships:
    database: "db:mysql"

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        opcache.preload: /app/config/preload.php

build:
    flavor: none

disk: 1024

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

workers:
    messenger:
        # PHP background workers usually don't require much CPU. See
        # https://symfony.com/doc/current/cloud/cookbooks/resources_allocation.html
        # for more information
        size: XS
        resources:
            base_memory: 64 # Keep in sync with the `memory-limit` flag value
            memory_ratio: 128
        commands:
            # Don't forget to update your receiver name(s)
            start: symfony console messenger:consume --time-limit=60 --memory-limit=128M

mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | (>&2 bash)

        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)
