monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: critical
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            handler: grouped
        grouped:
            type: group
            members: [ nested, deduplicated ]
        nested:
            type: stream
            path: php://stderr
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deduplicated:
            type: deduplication
            handler: symfony_mailer
        symfony_mailer:
            type: symfony_mailer
            from_email: 'noreply@example.com'
            to_email: 'christoph.steltner@gmail.com'
            subject: 'COIS - An Error Occurred! %%message%%'
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html
s
