#index:
#    path: /
#    controller: App\Controller\DefaultController::index

live_component:
    resource: "@LiveComponentBundle/Resources/config/routing/live_component.xml"
    # uncomment to add localization to your components
    #prefix: '/{_locale}'
