name: Continuous Integration

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    static-analysis:
        name: Static Analysis (PHP ${{ matrix.php-versions }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-versions: ["8.0", "8.1"]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}

            - name: Copy .env.test.local
              run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

            - name: Validate main `composer.json` and `composer.lock` files
              run: composer validate --no-check-version

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            - name: Analyse PHP Code (EasyCodingStandard)
              run: vendor/bin/ecs

            - name: Analyse PHP Code (PHPStan)
              run: |
                  php bin/console cache:warmup
                  vendor/bin/phpstan analyse

            - name: Analyse PHP Code (Psalm)
              run: vendor/bin/psalm

            - name: Cache node_modules
              uses: actions/cache@v1
              id: yarn-cache-node-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-cache-node-modules-
            - name: Yarn install
              if: steps.yarn-cache-node-modules.outputs.cache-hit != 'true'
              run: yarn install

            - name: Analyse JS (ESLint)
              run: yarn run eslint assets

            - name: Analyse JS Style (Pettier)
              run: yarn run prettier --check .

    tests:
        name: Tests (PHP ${{ matrix.php-versions }})
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: false
                    MYSQL_ROOT_PASSWORD: symfony
                    MYSQL_DATABASE: symfony
                ports:
                    - 3306/tcp
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        strategy:
            fail-fast: false
            matrix:
                php-versions: ["8.0", "8.1"]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}

            - name: Copy .env.test.local
              run: php -r "file_exists('.env.test.local') || copy('.env.github.test', '.env.test.local');"

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            - name: Run Migration
              run: php bin/console doctrine:schema:create || echo "No schema found or schema failed"
              env:
                  DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony

            - name: Cache node_modules
              uses: actions/cache@v1
              id: yarn-cache-node-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-cache-node-modules-

            - name: Yarn install
              if: steps.yarn-cache-node-modules.outputs.cache-hit != 'true'
              run: yarn install

            - name: Yarn build
              run: yarn run encore production

            - name: Execute tests via PHPUnit
              run: vendor/bin/phpunit
              env:
                  DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony

            - name: Upload coverage results to Coveralls
              if: ${{ github.actor != 'dependabot[bot]' }}
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  composer global require php-coveralls/php-coveralls
                  php-coveralls --coverage_clover=var/build/coverage/logs/clover.xml -v

            - name: Upload coverage to Codeclimate
              if: ${{ github.actor != 'dependabot[bot]' }}
              uses: paambaati/codeclimate-action@v3.0.0
              env:
                  CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
              with:
                  coverageLocations: ${{github.workspace}}/var/build/coverage/logs/clover.xml:clover
